save

diff --git a/bin/pre-push b/bin/pre-push
--- a/bin/pre-push
+++ b/bin/pre-push
@@ -1,4 +1,15 @@
 #!/bin/bash
-cd `dirname $0`
-cd ../../
-npm run lint
+ 
+# Ensure all JavaScript files staged for commit pass standard code style 
+function xargs-r() {
+  # Portable version of "xargs -r". The -r flag is a GNU extension that 
+  # prevents xargs from running if there are no input files. 
+  if IFS= read -r -d $'\n' path; then
+    { echo "$path"; cat; } | xargs $@
+  fi
+}
+git diff --name-only --cached --relative | grep '\.jsx\?$' | sed 's/[^[:alnum:]]/\\&/g' | xargs-r -E '' -t standard --verbose | snazzy
+if [[ $? -ne 0 ]]; then
+  echo 'JavaScript Standard Style errors were detected. Aborting commit.'
+  exit 1
+fi
